//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCAssignment2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieTable
    {
        public int MovieID { get; set; }
        public string MovieName { get; set; }
        public string MovieReleaseDate { get; set; }
    }
}
